language: go
go:
    - 1.3.3 # Pi version
    - 1.10 # Latest stable
    - tip
install:
    - go get github.com/tarm/serial
    - go get gopkg.in/yaml.v2
    - go get github.com/ricallinson/simplebdd
