GetStopChargeTemp: true
GetSerialNum: true
GetNumCells: true
GetCellRange: true
GetForceFan: true
GetFirstPosition: true
GetHighVoltage: true
GetMaxVoltage: true
GetMinVoltage: true
GetStopChargeUnderVoltage: true
GetRealTimeVoltage: true
GetLowVoltage: true
GetAddrTemp: true
GetCellsTemp: true
